### ISSUE TITLE
static-link is broken

### ISSUE THREAD

**Issue by Kek5chen** [jkvargas/russimp-sys#49]
Using static-link does not work on x86_64-linux-gnu (nightly).
Seems like -Werror is enabled upstream -> [This CMake Flag in assimp](https://github.com/assimp/assimp/blob/46c26eda5a3e212e086fc96b453ecb68f4b3ae75/CMakeLists.txt#L132)
I can't use the prebuilt feature either because then docs.rs fails to build docs as it can't fetch from the interweb.

Sucks when assimp doesn't manage to ship proper artifacts. Maybe a version bump resolves this?
*Even though this error actually looks like a compiler bug..*

The error log as well:
```
error: failed to run custom build command for `russimp-sys v2.0.2`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/homeless/target/debug/build/russimp-sys-796dbe7914b33d1d/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = Some("/nix/store/c6fjhl7knca7wrxc02qz3qkbc76lsbiq-patchelf-0.15.0:/nix/store/bz09w8ykfm1y5nn28bd0dqhwj5cnp781-update-autotools-gnu-config-scripts-hook:/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0:/nix/store/3zaigavb3ig42pb3rmg0cjr85d77aqwz-binutils-wrapper-2.41:/nix/store/9yc7hg7gnwswrqqm5slhajbs5f33mpsm-libxkbcommon-1.7.0-dev:/nix/store/zia652d8j3vmxqjqrf6wc9s4hfg2g3d5-libxkbcommon-1.7.0:/nix/store/jdfx8wiack71xp0y7lia3jziq0kl9s9i-libGL-1.7.0-dev:/nix/store/2r2hpjy4lwscjj4csn02jcac73mlr0yz-libGL-1.7.0:/nix/store/gjkh5awx8j3gp5951yy1wi7kalkj4bqf-libglvnd-1.7.0:/nix/store/03npki1znk16pai644gn4h058znfm8ck-libglvnd-1.7.0-dev:/nix/store/z9w9jh0pq94vlfzsiyb3g6lrai8ba2px-cmake-3.29.2:/nix/store/zk4s7cfbqdaba0dmg25n8dhpqkwqgzza-rust-bindgen-hook:/nix/store/gwxqkkagvqcbf5ac4jm246c6mg7nbp3h-gcc-13.2.0-lib:/nix/store/k1z5qw41pwsm1zm0n1i12mx5w0ca277m-zlib-1.3.1-static:/nix/store/cl11h6adnkl4yppb7gwswj494d8i7h09-pkg-config-wrapper-0.29.2:/nix/store/g7ar3xqp2hla6xvp8230nlniswi2mn1z-openssl-3.0.14-dev:/nix/store/bfsvw0q1i96g0kcr9i7qb6pix91a3mzj-openssl-3.0.14-bin:/nix/store/18b6frnaw53mwlcqssndd9n7z09x4f3d-openssl-3.0.14:/nix/store/4qaww4mqpwms6w83ci8z86jbbj4xp7ai-wayland-1.22.0-dev:/nix/store/fnqas516xgqcvdng5442x9wkpk7dirwq-wayland-1.22.0-bin:/nix/store/g5jpbchmig68nfnahq6kk5cswwj1niwb-wayland-1.22.0:/nix/store/ns1id703cisfzjmvg65wsdlbz1bvng5q-libXcursor-1.2.2-dev:/nix/store/8iiy57n7z1vdhl8zy7qp8pvlh9hx96in-libXcursor-1.2.2:/nix/store/fn2hqz897hb2hwjybzzcbaz53099nbdl-libXrandr-1.5.4-dev:/nix/store/b6n09p75n4dr8lnpzd2zajw9m17h4aaz-libXrender-0.9.11-dev:/nix/store/8zvwmjbhfa724bffp3jsi05snp8p6fpm-xorgproto-2024.1:/nix/store/vkfvqsrqp6sdpgqn1q5qn7nyvrf9alr0-libX11-1.8.9-dev:/nix/store/saxbjhw46yyi5c0vjm5hsnrsf8dggh1f-libxcb-1.17.0-dev:/nix/store/mpcnljkmd6r804wnvj3gdcms9d4ffyjf-libxcb-1.17.0:/nix/store/lkrbf19nr3z5knhczljnz4w7dkykyyz4-libX11-1.8.9:/nix/store/01kkjznjq85f4gas4brflcrpiflfcmbc-libXrender-0.9.11:/nix/store/h56a0s27dacncl4nv1mibh1gyj703g5x-libXrandr-1.5.4:/nix/store/kcmgbg3ma4fj6jw2vcx877phvhyw64q6-libXi-1.8.1-dev:/nix/store/dfiq24vzgk62pd5i4q5m0xdqjwb2qhhf-libXfixes-6.0.1-dev:/nix/store/3ylk82l5md1ymma3xb9m5k11khh3cxa7-libXfixes-6.0.1:/nix/store/j8m2icfksf4sd350yc2ap5yb6s5495hh-libXext-1.3.6-dev:/nix/store/yvx69h9wy9sx3xsg0w9gd5fnjx2snrh6-libXau-1.0.11-dev:/nix/store/5rlpqrpqh1wf0jzz8a5fabsg1irn649h-libXau-1.0.11:/nix/store/nzzy4v5mryd6q0p0gx9c3v0fw7fy7gkc-libXext-1.3.6:/nix/store/fb87ixpqm8mm5kq83vxvab5dm1vq202d-libXi-1.8.1:/nix/store/rgyhzi0bq57fgjqy371d31jlr2kja5wb-vulkan-headers-1.3.283.0:/nix/store/w0c5xnndp8r4m1ml3i4s7ngkn936c9p6-vulkan-loader-1.3.283.0-dev:/nix/store/igf36hrkvrjc6s6k1pc4f6vcp7z8g5c8-vulkan-loader-1.3.283.0:/nix/store/b2y6p250zafyx8zijyydf765n4y9k9ja-vulkan-validation-layers-1.3.283.0")
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/homeless/target/debug/build/russimp-sys-57bb1093544fccca/out/static/build" && CMAKE_PREFIX_PATH="/nix/store/c6fjhl7knca7wrxc02qz3qkbc76lsbiq-patchelf-0.15.0:/nix/store/bz09w8ykfm1y5nn28bd0dqhwj5cnp781-update-autotools-gnu-config-scripts-hook:/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0:/nix/store/3zaigavb3ig42pb3rmg0cjr85d77aqwz-binutils-wrapper-2.41:/nix/store/9yc7hg7gnwswrqqm5slhajbs5f33mpsm-libxkbcommon-1.7.0-dev:/nix/store/zia652d8j3vmxqjqrf6wc9s4hfg2g3d5-libxkbcommon-1.7.0:/nix/store/jdfx8wiack71xp0y7lia3jziq0kl9s9i-libGL-1.7.0-dev:/nix/store/2r2hpjy4lwscjj4csn02jcac73mlr0yz-libGL-1.7.0:/nix/store/gjkh5awx8j3gp5951yy1wi7kalkj4bqf-libglvnd-1.7.0:/nix/store/03npki1znk16pai644gn4h058znfm8ck-libglvnd-1.7.0-dev:/nix/store/z9w9jh0pq94vlfzsiyb3g6lrai8ba2px-cmake-3.29.2:/nix/store/zk4s7cfbqdaba0dmg25n8dhpqkwqgzza-rust-bindgen-hook:/nix/store/gwxqkkagvqcbf5ac4jm246c6mg7nbp3h-gcc-13.2.0-lib:/nix/store/k1z5qw41pwsm1zm0n1i12mx5w0ca277m-zlib-1.3.1-static:/nix/store/cl11h6adnkl4yppb7gwswj494d8i7h09-pkg-config-wrapper-0.29.2:/nix/store/g7ar3xqp2hla6xvp8230nlniswi2mn1z-openssl-3.0.14-dev:/nix/store/bfsvw0q1i96g0kcr9i7qb6pix91a3mzj-openssl-3.0.14-bin:/nix/store/18b6frnaw53mwlcqssndd9n7z09x4f3d-openssl-3.0.14:/nix/store/4qaww4mqpwms6w83ci8z86jbbj4xp7ai-wayland-1.22.0-dev:/nix/store/fnqas516xgqcvdng5442x9wkpk7dirwq-wayland-1.22.0-bin:/nix/store/g5jpbchmig68nfnahq6kk5cswwj1niwb-wayland-1.22.0:/nix/store/ns1id703cisfzjmvg65wsdlbz1bvng5q-libXcursor-1.2.2-dev:/nix/store/8iiy57n7z1vdhl8zy7qp8pvlh9hx96in-libXcursor-1.2.2:/nix/store/fn2hqz897hb2hwjybzzcbaz53099nbdl-libXrandr-1.5.4-dev:/nix/store/b6n09p75n4dr8lnpzd2zajw9m17h4aaz-libXrender-0.9.11-dev:/nix/store/8zvwmjbhfa724bffp3jsi05snp8p6fpm-xorgproto-2024.1:/nix/store/vkfvqsrqp6sdpgqn1q5qn7nyvrf9alr0-libX11-1.8.9-dev:/nix/store/saxbjhw46yyi5c0vjm5hsnrsf8dggh1f-libxcb-1.17.0-dev:/nix/store/mpcnljkmd6r804wnvj3gdcms9d4ffyjf-libxcb-1.17.0:/nix/store/lkrbf19nr3z5knhczljnz4w7dkykyyz4-libX11-1.8.9:/nix/store/01kkjznjq85f4gas4brflcrpiflfcmbc-libXrender-0.9.11:/nix/store/h56a0s27dacncl4nv1mibh1gyj703g5x-libXrandr-1.5.4:/nix/store/kcmgbg3ma4fj6jw2vcx877phvhyw64q6-libXi-1.8.1-dev:/nix/store/dfiq24vzgk62pd5i4q5m0xdqjwb2qhhf-libXfixes-6.0.1-dev:/nix/store/3ylk82l5md1ymma3xb9m5k11khh3cxa7-libXfixes-6.0.1:/nix/store/j8m2icfksf4sd350yc2ap5yb6s5495hh-libXext-1.3.6-dev:/nix/store/yvx69h9wy9sx3xsg0w9gd5fnjx2snrh6-libXau-1.0.11-dev:/nix/store/5rlpqrpqh1wf0jzz8a5fabsg1irn649h-libXau-1.0.11:/nix/store/nzzy4v5mryd6q0p0gx9c3v0fw7fy7gkc-libXext-1.3.6:/nix/store/fb87ixpqm8mm5kq83vxvab5dm1vq202d-libXi-1.8.1:/nix/store/rgyhzi0bq57fgjqy371d31jlr2kja5wb-vulkan-headers-1.3.283.0:/nix/store/w0c5xnndp8r4m1ml3i4s7ngkn936c9p6-vulkan-loader-1.3.283.0-dev:/nix/store/igf36hrkvrjc6s6k1pc4f6vcp7z8g5c8-vulkan-loader-1.3.283.0:/nix/store/b2y6p250zafyx8zijyydf765n4y9k9ja-vulkan-validation-layers-1.3.283.0" "cmake" "/homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/russimp-sys-2.0.2/assimp" "-DBUILD_SHARED_LIBS=OFF" "-DASSIMP_BUILD_ASSIMP_TOOLS=OFF" "-DASSIMP_BUILD_TESTS=OFF" "-DASSIMP_BUILD_ZLIB=ON" "-DLIBRARY_SUFFIX=" "-DCMAKE_INSTALL_PREFIX=/homeless/target/debug/build/russimp-sys-57bb1093544fccca/out/static" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0/bin/gcc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0/bin/g++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0/bin/gcc" "-DCMAKE_BUILD_TYPE=Release"
  -- Shared libraries disabled
  -- GCC13 detected disabling "-Wdangling-reference" in Cpp files as it appears to be a false positive
  -- compiling zlib from sources
  -- GCC13 detected disabling "-Warray-bounds and -Wstringop-overflow" for AssetLib/MDL/MDLLoader.cpp as it appears to be a false positive
  -- tinyusdz disabled
  -- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IQM IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
  -- Disabled importer formats: USD
  -- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF PBRT ASSJSON STEP
  -- Disabled exporter formats:
  -- Treating all warnings as errors (for assimp library only)
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /homeless/target/debug/build/russimp-sys-57bb1093544fccca/out/static/build
  running: cd "/homeless/target/debug/build/russimp-sys-57bb1093544fccca/out/static/build" && MAKEFLAGS="-j --jobserver-fds=8,9 --jobserver-auth=8,9" "cmake" "--build" "." "--target" "install" "--config" "Release"
  [  7%] Built target zlibstatic
  [  7%] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/AMF/AMFImporter_Geometry.cpp.o
  --- stderr
  In file included from /homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/russimp-sys-2.0.2/assimp/include/assimp/XmlParser.h:46,
                   from /homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/russimp-sys-2.0.2/assimp/code/AssetLib/AMF/AMFImporter.hpp:57,
                   from /homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/russimp-sys-2.0.2/assimp/code/AssetLib/AMF/AMFImporter_Geometry.cpp:44:
  In function ‘char_t ai_tolower(char_t) [with char_t = const char*]’,
      inlined from ‘void Assimp::AMFImporter::ParseNode_Coordinates(Assimp::XmlNode&)’ at /homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/russimp-sys-2.0.2/assimp/code/AssetLib/AMF/AMFImporter_Geometry.cpp:168:75:
  /homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/russimp-sys-2.0.2/assimp/include/assimp/StringUtils.h:224:53: error: offset ‘32’ outside bounds of constant string [-Werror=array-bounds=]
    224 |     return (in >= (char_t)'A' && in <= (char_t)'Z') ? (char_t)(in + 0x20) : in;
        |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  make[2]: *** [code/CMakeFiles/assimp.dir/build.make:1056: code/CMakeFiles/assimp.dir/AssetLib/AMF/AMFImporter_Geometry.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:169: code/CMakeFiles/assimp.dir/all] Error 2
  make: *** [Makefile:136: all] Error 2
  thread 'main' panicked at /homeless/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.51/src/lib.rs:1100:5:
  command did not execute successfully, got: exit status: 2
  build script failed, must exit now
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/d49be02cf6d2e2a01264fcdef1e20c826710c0f5/library/std/src/panicking.rs:681:5
     1: core::panicking::panic_fmt
               at /rustc/d49be02cf6d2e2a01264fcdef1e20c826710c0f5/library/core/src/panicking.rs:75:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::build_from_source
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Thank you so much and I hope you get around to maintaining this a bit more actively.

**Comment by Davidos533** [comment]
have same error, please fix it

**Comment by jkvargas** [comment]
Hi, 
I don't have time to put on russimp for now.
I am accepting PRs though

**Comment by Kek5chen** [comment]
If you don't think you have the time. Is this project abandoned? Since it took you like 3 months to respond it feels that way. If that's the case, are you looking for adopters? I'm not making a PR on a dead repo.

**Comment by jkvargas** [comment]
Its not very often to get a PR on russimp, thats the biggest reason I don't check the repo often.
I don't plan to abandon the project.
Feel free to send the PR and I will review it.

**Comment by tirbofish** [comment]
my PR that i created only works for linux, mac (not tested coz im broke) and WSL. in terms of windows, it is extremely confusing :/ if someone could take a look at it and create their own PR, it would be very nice :)
